### ISSUE TITLE
'panic: connect to cacher: lookup srv record, no such host' when used with MIRROR_HOST

### ISSUE THREAD

**Issue by vielmetti** [tinkerbell/boots#13]
See https://github.com/tinkerbell/boots/blob/9d6cded511d1e7678ec601a29aac4137f25ecb5a/env/mirror.go#L49 and following - 

The function buildMirrorBaseURL offers three options for setting a mirror site:

- set MIRROR_BASE_URL
- set MIRROR_HOST
- FacilityCode

If you use the FacilityCode option, it hard-codes a packet.net address. But if you set MIRROR_HOST you get further.

When I run

`ROLLBAR_TOKEN=foo PACKET_ENV=bar PACKET_VERSION=bletch API_CONSUMER_TOKEN=baz API_AUTH_TOKEN=xyzzy MIRROR_HOST=127.0.0.1 FACILITY_CODE=ARB1 ./boots`

I get this error

`panic: connect to cacher: lookup srv record: lookup _http._tcp.cacher.ARB1.packet.net on 192.168.1.254:53: no such host`

**Comment by vielmetti** [comment]
more specifically this error log:

```
ed@iyengar:~/src/github.com/tinkerbell/boots$ ROLLBAR_TOKEN=foo PACKET_ENV=bar PACKET_VERSION=bletch API_CONSUMER_TOKEN=baz API_AUTH_TOKEN=xyzzy MIRROR_HOST=127.0.0.1 FACILITY_CODE=ARB1 ./boots
{"level":"info","ts":1586176933.2510283,"caller":"boots/main.go:54","msg":"starting","service":"github.com/tinkerbell/boots","pkg":"main","version":"9d6cded"}
{"level":"error","ts":1586176936.9251387,"caller":"boots/main.go:58","msg":"connect to cacher: lookup srv record: lookup _http._tcp.cacher.ARB1.packet.net on 192.168.1.254:53: no such host","service":"github.com/tinkerbell/boots","pkg":"main","error":"connect to cacher: lookup srv record: lookup _http._tcp.cacher.ARB1.packet.net on 192.168.1.254:53: no such host","errorVerbose":"lookup _http._tcp.cacher.ARB1.packet.net on 192.168.1.254:53: no such host\nlookup srv record\ngithub.com/packethost/cacher/client.New.func1\n\t/home/ed/go/pkg/mod/github.com/packethost/cacher@v0.0.0-20200319200613-5dc1cac4fd33/client/main.go:22\ngithub.com/packethost/cacher/client.New\n\t/home/ed/go/pkg/mod/github.com/packethost/cacher@v0.0.0-20200319200613-5dc1cac4fd33/client/main.go:34\ngithub.com/tinkerbell/boots/packet.NewClient\n\t/home/ed/src/github.com/tinkerbell/boots/packet/client.go:45\nmain.main\n\t/home/ed/src/github.com/tinkerbell/boots/main.go:56\nruntime.main\n\t/usr/lib/go-1.13/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/lib/go-1.13/src/runtime/asm_arm64.s:1128\nconnect to cacher\ngithub.com/tinkerbell/boots/packet.NewClient\n\t/home/ed/src/github.com/tinkerbell/boots/packet/client.go:47\nmain.main\n\t/home/ed/src/github.com/tinkerbell/boots/main.go:56\nruntime.main\n\t/usr/lib/go-1.13/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/lib/go-1.13/src/runtime/asm_arm64.s:1128"}
2020/04/06 08:42:17 Rollbar error: received response: 401 Unauthorized
Rollbar item failed to send: map[access_token:foo data:map[body:map[trace_chain:[map[exception:map[class:rollbar.rError message:connect to cacher: lookup srv record: lookup _http._tcp.cacher.ARB1.packet.net on 192.168.1.254:53: no such host] frames:[{/home/ed/src/github.com/tinkerbell/boots/packet/client.go github.com/tinkerbell/boots/packet.NewClient 47} {/home/ed/src/github.com/tinkerbell/boots/main.go main.main 56} {/usr/lib/go-1.13/src/runtime/proc.go runtime.main 203} {/usr/lib/go-1.13/src/runtime/asm_arm64.s runtime.goexit 1128}]] map[exception:map[class:errors.withStack message:connect to cacher: lookup srv record: lookup _http._tcp.cacher.ARB1.packet.net on 192.168.1.254:53: no such host] frames:[]]]] code_version:bletch environment:bar language:go level:error notifier:map[name:rollbar/rollbar-go version:1.0.1] platform:linux server:map[host:iyengar root:/github.com/tinkerbell/boots] timestamp:1586176936 title:connect to cacher: lookup srv record: lookup _http._tcp.cacher.ARB1.packet.net on 192.168.1.254:53: no such host]]
panic: connect to cacher: lookup srv record: lookup _http._tcp.cacher.ARB1.packet.net on 192.168.1.254:53: no such host

goroutine 1 [running]:
github.com/packethost/pkg/log.Logger.Fatal(0x64397e, 0x1b, 0x400000e070, 0x4000276240, 0x716840, 0x400000c3e0, 0x0, 0x0, 0x0)
        /home/ed/go/pkg/mod/github.com/packethost/pkg@v0.0.0-20190715213007-7c3a64b4b5e3/log/log.go:119 +0xb0
main.main()
        /home/ed/src/github.com/tinkerbell/boots/main.go:58 +0x824
```

**Comment by nathangoulding** [comment]
@vielmetti Is this still valid after the improvements we've made?

**Comment by vielmetti** [comment]
@nathangoulding I'll give it a test with a fresh checkout.

**Comment by mmlb** [comment]
@vielmetti there are 2 options here:

1. If you do want to run in cacher mode
    1. Set CACHER_CERT_URL and CACHER_GRPC_AUTHORITY, and it'll avoid the SRV look ups
2. If you actually want to use tinkerbell mode instead:
    1. Set DATA_MODEL_VERSION=1 (to set boots to tinkerbell mode), TINKERBELL_CERT_URL, and TINKERBELL_GRPC_AUTHORITY to avoid SRV look ups

I suspect you want option 2. Also https://github.com/tinkerbell/sandbox/ maybe does everything you want?

**Comment by jacobweinstock** [comment]
Hey @vielmetti, looks like it's been quite a while. are you still experiencing this?

**Comment by vielmetti** [comment]
This can be closed - so much has changed since I reported it and it's not a current concern.
